# Generated by Django 4.2.3 on 2024-12-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('location_type', models.CharField(max_length=40)),
                ('compensation', models.CharField(max_length=50)),
                ('employment_type', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('job_details', models.TextField()),
            ],
        ),
    ]
